#!/bin/bash

release="$(lsb_release -d)"

[[ "$release" == *Arch\ Linux* ]] && \
	echo "this module does not yet work on Arch Linux" && exit 0

[[ "$release" == *Ubuntu* ]] || [[ "$release" == *Debian* ]] && \
	sudo apt install git build-essential openjdk-11-jre-headless -y

# use a seperate user for the server for security reasons
sudo useradd -r -m -U -d /opt/minecraft -s /bin/bash minecraft

# as the new user, set up the rcon client and minecraft server
sudo -i -u minecraft << EOF
mkdir ~/backups ~/tools ~/server
git clone https://github.com/Tiiffi/mcrcon.git ~/tools/mcrcon

cd ~/tools/mcrcon
make

cd ~/server
curl "$(curl https://www.minecraft.net/en-us/download/server | grep -i '.jar' | grep -i href | cut -d '"' -f2)" -o server.jar
echo 'eula=true' > eula.txt
EOF

# create a systemd service for the server
sudo mkdir -p /etc/systemd/system/
sudo touch /etc/systemd/system/minecraft.service

echo '[Unit]
Description=Minecraft Server
After=network.target

[Service]
User=minecraft
Nice=1
KillMode=none
SuccessExitStatus=0 1
ProtectHome=true
ProtectSystem=full
PrivateDevices=true
NoNewPrivileges=true
WorkingDirectory=/opt/minecraft/server
ExecStart=/usr/bin/java -Xmx3072M -Xms3072M -jar server.jar nogui
ExecStop=/opt/minecraft/tools/mcrcon/mcrcon -H 127.0.0.1 -P 25575 -p password stop

[Install]
WantedBy=multi-user.target' | sudo tee /etc/systemd/system/minecraft.service

echo "if you wish to use rcon with the server, you must set the rcon password and port manually in /opt/minecraft/server/server.properties, as well as enable rcon in the same file"
