#!/bin/bash

release="$(lsb_release -d)"

[[ "$release" == *Arch\ Linux* ]] && \
	echo "this module does not yet work on Arch Linux" && exit 0

[[ "$release" == *Ubuntu* ]] || [[ "$release" == *Debian* ]] && \
	sudo apt install git build-essential openjdk-11-jre-headless -y

# use a seperate user for the server for security reasons
useradd -r -m -U -d /opt/minecraft minecraft

sudo -i -u minecraft << EOF
mkdir ~/backups ~/tools ~/server
git clone https://github.com/Tiiffi/mcrcon.git ~/tools/mcrcon

cd ~/tools/mcrcon
make

cd ~/server
curl "$(curl https://www.minecraft.net/en-us/download/server | grep -i '.jar' | grep -i href | cut -d '"' -f2)" -o server.jar
echo 'eula=true' > eula.txt
EOF
