#!/bin/bash

sudo -v

# handle args
for arg in $*; do
	case $arg in
		"-ubuntu")
			./ubuntu-server/first-time-setup
			;;
		"+pi-hole")
			./configurations/pi-hole
			;;
		"+nas")
			./configurations/nas
			;;
	esac
done

# vim: syntax=sh
