#!/bin/bash

sudo -v

# handle args
for arg in $*; do
	case $arg in
		"-ubuntu")
			./ubuntu-server/first-time-setup
			;;
		+*)
			_arg="$(echo $arg | sed 's/+//')"
			[ -f "./modules/$_arg" ] || echo "invalid module \"$_arg\", skipping" && continue
			./modules/$_arg
			;;
		"+nas")
			./configurations/nas
			;;
	esac
done

# vim: syntax=sh
