#!/bin/bash

# get sudo permissions for this script
sudo -v

# get new hostname to set
echo "please enter a new hostname, or press enter to skip:"
read new_hostname
# attempt to set new hostname if not empty
[ ! -z "$new_hostname" ] && sudo hostnamectl set-hostname $new_hostname

# update
sudo apt update
sudo apt upgrade -y

# remove snapd
sudo systemctl disable --now snapd
sudo apt remove --purge snapd -y

# prevent automatic reinstallation of snapd from future updates
sudo apt-mark hold snapd

# delete motd ads (really, canonical?)
sudo rm -rf /etc/update-motd.d/*motd-news

# attempt to install all programs listed under install_list
echo "attempting to install all programs listed under Pi-config/ubuntu-server/install_list"
for entry in $(cat install_list); do
	install_list="$install_list $entry"
done

# if install list is empty, don't try to install anything
[ ! -z "$install_list" ] && sudo apt install $install_list -y
